#include "openrc/rac_integer_glyph.hpp"

#include <bit>
#include <fstream>
#include <iostream>
#include <stdexcept>

namespace {
using namespace openrc;
void check(bool condition, const char *message) { if (!condition) throw std::runtime_error(message); }
template<class F> void rejects(F call) {
  try { call(); } catch (const RacIntegerGlyphError &) { return; }
  throw std::runtime_error("Invalid integer glyph input was accepted");
}
std::vector<std::byte> bytes(std::initializer_list<unsigned> values) {
  std::vector<std::byte> out; for (auto v : values) out.push_back(static_cast<std::byte>(v)); return out;
}
RacFontMetricTableV1 font() {
  RacFontMetricTableV1 result;
  result.rows[65] = {16, 32, -2, 6};
  result.rows[32] = {0, 0, 0, 4};
  result.rows[1] = {24, 48, 3, 25};
  result.rows[128] = {48, 32, -1, 7};
  result.rows[192] = {64, 16, -5, -3};
  return result;
}
void dispatch_and_wrapping() {
  auto metrics = font();
  RacIntegerGlyphInputsV1 in;
  in.x_word = 100; in.y_word = 50; in.rgbaq = UINT64_C(0xfedcba9880402010);
  in.tex0 = UINT64_C(0x8123456789abcdef);
  in.screen_offset_words = {0x8000, 0x7800};
  const auto out = execute_rac_integer_glyph_v1(bytes({65,32,128,1,66,0}), metrics, in);
  check(out.consumed_bytes == 5 && out.reached_nul && out.draws.size() == 4,
        "Original space/empty/accent/icon dispatch differs");
  check(out.draws[0].arguments.rectangle_words == std::array<std::uint32_t,4>{100,48,16,16} &&
        out.draws[1].arguments.rectangle_words == std::array<std::uint32_t,4>{107,45,16,16} &&
        out.draws[2].arguments.rectangle_words == std::array<std::uint32_t,4>{110,49,16,16} &&
        out.draws[3].arguments.rectangle_words == std::array<std::uint32_t,4>{117,53,24,16},
        "Signed offsets, accent ordering or source cell sizes differ");
  check(out.draws[1].source_call_pc == 0x1f6794 && out.draws[3].source_call_pc == 0x1f6838 &&
        out.draws[3].arguments.rgbaq == UINT64_C(0xffffffff80252525) &&
        out.draws[2].arguments.rgbaq == in.rgbaq && out.final_x_word == 142,
        "Raw argument color or word advance differs");
  check(out.draws[0].emission.coordinate_words ==
          std::array<std::uint32_t,4>{0x7e38,0x7f38,0x82f8,0x83f8},
        "Original quad packet did not receive glyph coordinates");
  in.x_word = 0xfffffffe; in.y_word = 1;
  const auto wrap = execute_rac_integer_glyph_v1(bytes({65,0}), metrics, in);
  check(wrap.final_x_word == 4 && wrap.draws[0].arguments.rectangle_words[1] == 0xffffffff,
        "Integer glyph wrapping was normalized or saturated");
}
void palette_and_termination() {
  RacIntegerGlyphInputsV1 in;
  in.rgbaq = UINT64_C(0x1234567880123456);
  in.palette[1] = 0xffaabbcc;
  auto out = execute_rac_integer_glyph_v1(bytes({9,65,8,65,0}), font(), in);
  check(out.draws[0].arguments.rgbaq == 0x80aabbcc &&
        out.draws[1].arguments.rgbaq == 0x80123456 &&
        out.final_palette[0] == 0x80123456,
        "Inline colors failed to preserve alpha/reseed slot zero/clear high bits");
  in.inline_colors_enabled = false;
  out = execute_rac_integer_glyph_v1(bytes({9,65,0}), font(), in);
  check(out.draws[0].arguments.rgbaq == in.rgbaq && out.consumed_bytes == 2,
        "Disabled control bytes altered color or drew a glyph");
  in.preserve_palette_zero = true; in.palette[0] = 123; in.byte_limit = 0;
  out = execute_rac_integer_glyph_v1({}, font(), in);
  check(!out.palette_zero_written && out.final_palette[0] == 123 && !out.reached_nul,
        "Empty source limit changed preserved palette or read text");
  in.byte_limit = 1;
  out = execute_rac_integer_glyph_v1(bytes({65}), font(), in);
  check(out.draws.size() == 1 && !out.reached_nul, "Exact byte limit read an unowned terminator");
  in.byte_limit = -1;
  rejects([&] { (void)execute_rac_integer_glyph_v1(bytes({65}), font(), in); });
  rejects([&] { (void)execute_rac_integer_glyph_v1(bytes({232,0}), font(), in); });
  rejects([&] { (void)execute_rac_integer_glyph_v1(bytes({128,0}), font(), in, {1,1}); });
  rejects([&] { (void)execute_rac_integer_glyph_v1(bytes({9,9,0}), font(), in, {1,10}); });
}

// Optional ignored corpus generated by actual original instruction execution.
// The ordinary CTest invocation needs no original data or external fixture.
void source_corpus(const char *path) {
  std::ifstream file(path, std::ios::binary);
  const auto read = [&](unsigned count) {
    std::uint64_t value = 0;
    for (unsigned i=0;i<count;++i) { const int byte=file.get(); check(byte>=0,"Truncated source corpus"); value |= std::uint64_t(byte)<<(8U*i); }
    return value;
  };
  check(read(4)==0x31474952U,"Wrong integer glyph source corpus");
  const auto count=read(4); check(count && count<=10000,"Unbounded source cases");
  std::uint64_t draws=0;
  for(std::uint64_t c=0;c<count;++c) {
    RacIntegerGlyphInputsV1 in;
    in.x_word=static_cast<std::uint32_t>(read(4)); in.y_word=static_cast<std::uint32_t>(read(4));
    in.byte_limit=std::bit_cast<std::int64_t>(read(8)); in.rgbaq=read(8); in.tex0=read(8);
    for(auto &v:in.palette) v=static_cast<std::uint32_t>(read(4));
    in.inline_colors_enabled=read(4)!=0; in.preserve_palette_zero=read(4)!=0;
    for(auto &v:in.screen_offset_words) v=static_cast<std::uint32_t>(read(4));
    std::array<std::byte,kRacFontMetricTableBytesV1> raw{};
    for(auto &v:raw) v=static_cast<std::byte>(read(1));
    const auto size=read(4); check(size<=65536,"Unbounded source text");
    std::vector<std::byte> text(size); for(auto &v:text) v=static_cast<std::byte>(read(1));
    const auto out=execute_rac_integer_glyph_v1(text,parse_rac_font_metric_table_v1(raw),in);
    check(out.consumed_bytes==read(4) && out.final_x_word==read(4) &&
          out.final_rgbaq==read(8),"Original integer glyph final scalar state differs");
    for(auto v:out.final_palette) check(v==read(4),"Original glyph palette differs");
    const auto n=read(4); check(n==out.draws.size(),"Original glyph draw count differs"); draws+=n;
    for(const auto &draw:out.draws) {
      check(draw.source_call_pc==read(4),"Original glyph call site differs");
      for(auto byte:draw.emission.packet) check(std::to_integer<unsigned>(byte)==read(1),"Original glyph packet bytes differ");
    }
  }
  check(file.get()==EOF,"Trailing source corpus bytes");
  std::cout<<"integer glyph original source: cases="<<count<<" draws="<<draws<<'\n';
}
} // namespace
int main(int argc,char **argv) {
  try {
    dispatch_and_wrapping(); palette_and_termination();
    if(argc==2) source_corpus(argv[1]); else check(argc==1,"Unexpected source corpus arguments");
    std::cout<<"Integer glyph tests passed\n"; return 0;
  } catch(const std::exception &error) { std::cerr<<error.what()<<'\n'; return 1; }
}
